[package]
name = "garnold24/push-your-friends"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Promise = "evaera/promise@4.0.0"
React = "core-packages/react@17.0.1-rc.19"
ReactRoblox = "core-packages/react-roblox@17.0.1-rc.19"
Flipper = "reselim/flipper@2.0.0"
Signal = "sleitnick/signal@1.5.0"
Comm = "sleitnick/comm@0.3.1"
Trove = "sleitnick/trove@0.5.0"
Sift = "csqrl/sift@0.0.6"
Symbol = "sleitnick/symbol@2.0.1"
GameAnalytics = "gameanalytics/gameanalytics-sdk@2.2.2"
Observers = "sleitnick/observers@^0.3.3"

[server-dependencies]
Cmdr = "evaera/cmdr@1.11.0"
DataStore2 = "nidoxs/datastore2@1.4.0"